### ISSUE TITLE
支持外部SPI FLASH

### ISSUE THREAD

**Issue by zsjlovestudy** [100askTeam/lv_chinese_ime#1]
您好，我有下面两个问题想请教一下。
1.这个后面有做当候选字大于一行时，可以上下一上选择其它备选字，或者拖动选择其它未显示的备选词。
2.还有就是关于外部存储的问题，字库放到外部不是很难，这个词库要如何自己制作呢，如何也放到外部哈。

**Comment by YobieZhou** [comment]
1. 现在的版本候选字只有一行(可以左右滑动文字候选栏展示候选字)，没有像手机那样有个下拉框展示多行候选字。
2. LVGL提供了文件系统接口，当然你也可以使用其他文件系统接口读取字库和词库文件，字库和词库的参考请看仓库目录：/test/README.md 文件。
 
ps：
1. 字库可以自己制作(http://lvgl.100ask.net/master/tools/fonts-zh-source.html)
2. 词库需要按照json格式自定义(/test/zh_cn_pinyin_dict.json)
